Import('env')

env.Append(CPPPATH=[Dir('.')])

env.add_sources([
'Routing.cc',
'SimpleRouting.cc',
'PredefinedTreeRouting.cc',
'AODV.cc'
])

if env.conf.has_key('neighborhood') and env.conf.bool('neighborhood'):
    env.add_sources(['GPSR.cc'])

if env.get_platform() == 'omnet':
	env.add_sources([
	'ClusterBasedFlooding.cc',
	'CounterBasedFlooding.cc',
	'DHRouting.cc',
	'ProbabilisticFlooding.cc',
	'SectorLocationBasedRouting.cc',
	'ShortCuttingTreeRouting.cc',
	'SourceTreeRouting.cc',
	'TransmissionDelayMonitor.cc',
	'TreeRouting.cc'
	])

