Import('env')

env.conf_to_bool_define(['fnet'])

env.Append(CPPPATH=[Dir('.')])
env.Append(CPPPATH=[Dir('../../s25fl/')])
env.Append(CPPPATH=[Dir('../../../common/')])

env.add_sources([
'main.cc',
'bootloader.cc'
])

