Import('env')

env.Append(CPPPATH=[Dir('.')])

env.add_sources([
'RFA1DriverLayer.cc',
'tasklet.cc',
'tosUtil.cc'
])

if env.conf.str('mac') == 'tos':
    env.add_sources([
    'RadioAlarm.cc',
    '802154CsmaLayer.cc',
    #'TosRandomCollisionLayer.cc',
    'TosAdaptionLayer.cc',
    'UniqueLayer.cc',
    'PacketLinkLayer.cc',
    'MessageBufferLayer.cc',
    'SoftwareAckLayer.cc',
    'CcaLayer.cc'
    ])

