Import('env')

if env.conf.has_key('rf_spi_port'):
	env.conf_to_str_define(['rf_spi_port'])
	
if env.conf.has_key('external_flash'):
	env.conf_to_bool_define(['external_flash'])
	
if env.conf.has_key('serial_baudrate'):
	env.conf_to_str_define(['serial_baudrate'])
	
if env.conf.has_key('serial_comm_baudrate'):
	env.conf_to_str_define(["serial_comm_baudrate"])
	
env.conf_to_str_define(['mac_default_tx_power_lvl'])
env.conf_to_str_define(['mac_default_rx_pdt_level'])

env.Append(CPPPATH=[Dir('.')])

env.add_sources([
'palLed.cc',
'pal.cc',
'palFirmwareDummy.cc',
'palExecUtils.cc',
'palRand.cc',
'MacSymbolCounter.cc'
])


SConscript("../../chips/STM32F103/SConscript")
SConscript("../../chips/AT86RF231/SConscript")
SConscript("../../chips/N25Q128A/SConscript")

if env.conf.bool('pal_mac'):
	SConscript("mac_common/SConscript")

	mc = env.conf.str('mac', valid_values=['tos','dsme','pure_sniffer'])

	if mc == 'tos' or mc == 'pure_sniffer':
	    SConscript("tosMac/SConscript")
	elif mc == 'dsme':
 		env.Append(CPPDEFINES=["DSME"])
		SConscript("dsme/SConscript")
		SConscript("tosMac/SConscript")
		#env.add_sources(['timer1.cc'])
