Import('env')

env.Append(CPPPATH=[Dir('.')])

env.add_sources([
'palLed.cc',
'palSerial.cc',
'pal.cc',
'palGPIOPin.cc',
'memory.cc',
'palTwiMaster.cc',
'palTwiSlave.cc',
'palFirmwareDummy.cc'
])

# for RS232
if env.cometos_externals_path == '':
    error_no_externals()
    exit(1) 

env.conf_to_str_define(["serial_comm_baudrate"])
SConscript("../../chips/x86/SConscript")

	