Import('env')

env.Append(CPPPATH=[Dir('.')])

env.add_sources([
'Message.cc',
'Module.cc',
'cometos.cc',
])

if not env.get_platform() == 'local' and not env.get_platform() == 'python':
    SConscript('memory/SConscript')
