# The only reason this file exists is because MakeMake
# expects a custom makefile to be present in the directory.
# The actual targets required for gmock are in the modules.mk
# file of this directory
all:
clean:
depend: