Import('env')

env.Append(CPPPATH=[Dir('.')])

env.add_sources([
'FileManager.cc',
'FileSystem.cc',
'CFSArbiter.cc',
'CFSFormat.cc',
'CFSSegmentedFile.cc',
'CFSParameterStore.cc',
'SegFileFactoryImpl.cc'
])
