Import('env')
import glob

env.conf_to_bool_define(['mac_enable_stats'])
env.optional_conf_to_str_define(['serial_comm_payload_use'])

env.Append(CPPPATH=[Dir('.')])

env.add_sources([
'CommAssessment.cc',
'CsmaMac.cc',
'ForwardMacMeta.cc',
'MacHeader.cc',
'MacAbstractionBase.cc',
'MacControl.cc',
'MacStats.cc',
'PhyCount.cc',
'MacConfig.cc',
'NetworkInterfaceSwitch.cc',
'SimpleCsmaMac.cc'
])

if env.get_platform() == 'omnet':
	SConscript("omnetpp/SConscript")
