Import('env')

env.Append(CPPPATH=[Dir('.')])

env.add_sources([
'Delegate.cc',
'Message.cc',
'Module.cc',
'palExec.cc',
'palLed.cc',
'palLocation.cc',
'palLocalTime.cc',
'palId.cc',
'logging.cc',
'simUtil.cc',
'SchedulerModule.cc'
])

