Import('env')

env.Append(CPPPATH=[Dir('.')])

SConscript("tosMac/SConscript")

env.add_sources([
'MacAbstractionLayer.cc'
])

env.conf_to_str_define([
'mac_default_channel',
'MAC_DEFAULT_NWK_ID',
'MAC_DEFAULT_FRAME_RETRIES',
'MAC_DEFAULT_CCA_THRESHOLD',
'MAC_DEFAULT_MAX_CCA_RETRIES',
'MAC_DEFAULT_CCA_MODE',
'MAC_DEFAULT_MIN_BE',
'MAC_DEFAULT_MAX_BE',
'MAC_DEFAULT_TX_POWER_LVL'
])
